<?php
/**
 * Documentation Renderer for InstaWP Integration Plugin
 *
 * Renders markdown documentation files inside the WordPress admin.
 *
 * @package IWP
 * @since 0.0.5
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

class IWP_Docs_Renderer {

    /**
     * Ordered docs manifest: slug => title
     *
     * @var array
     */
    private $docs = array(
        'index'                    => 'Documentation Home',
        'getting-started'          => 'Getting Started',
        'settings'                 => 'Plugin Settings',
        'woocommerce-products'     => 'WooCommerce Products',
        'orders-and-site-creation' => 'Orders & Site Creation',
        'managing-sites'           => 'Managing Sites',
        'customer-experience'      => 'Customer Experience',
        'shortcodes'               => 'Shortcodes',
        'subscriptions'            => 'Subscriptions',
        'upgrade-downgrade'        => 'Upgrade & Downgrade',
        'advanced-features'        => 'Advanced Features',
        'troubleshooting'          => 'Troubleshooting',
    );

    /**
     * Parsedown instance
     *
     * @var Parsedown
     */
    private $parsedown;

    /**
     * Constructor
     */
    public function __construct() {
        if (!class_exists('Parsedown')) {
            require_once IWP_PLUGIN_PATH . 'includes/core/lib/Parsedown.php';
        }
        $this->parsedown = new Parsedown();
        $this->parsedown->setSafeMode(true);
    }

    /**
     * Render the full docs viewer (sidebar + content)
     *
     * @param string $active_slug The currently active doc slug
     */
    public function render($active_slug = 'index') {
        // Validate slug
        if (!array_key_exists($active_slug, $this->docs)) {
            $active_slug = 'index';
        }

        $content_html = $this->get_doc_html($active_slug);

        $this->render_docs_css();
        ?>
        <div class="iwp-docs-viewer">
            <nav class="iwp-docs-sidebar">
                <ul>
                    <?php foreach ($this->docs as $slug => $title) : ?>
                        <li class="<?php echo $slug === $active_slug ? 'active' : ''; ?>">
                            <a href="#" data-doc="<?php echo esc_attr($slug); ?>">
                                <?php echo esc_html($title); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </nav>
            <div class="iwp-docs-content" id="iwp-docs-content">
                <?php echo $content_html; // Already sanitized in get_doc_html ?>
            </div>
        </div>
        <?php
        $this->render_docs_script();
    }

    /**
     * Get parsed HTML for a given doc slug
     *
     * @param string $slug Doc slug
     * @return string Sanitized HTML
     */
    private function get_doc_html($slug) {
        $file_path = IWP_PLUGIN_PATH . 'docs/' . $slug . '.md';

        if (!file_exists($file_path)) {
            return '<p>' . esc_html__('Documentation file not found.', 'iwp-wp-integration') . '</p>';
        }

        $markdown = file_get_contents($file_path);
        if ($markdown === false) {
            return '<p>' . esc_html__('Could not read documentation file.', 'iwp-wp-integration') . '</p>';
        }

        // Rewrite internal markdown links to JS-friendly links
        // e.g. [Settings](settings.md) → <a href="#" data-doc="settings">Settings</a>
        $markdown = preg_replace_callback(
            '/\[([^\]]+)\]\(([a-z0-9-]+)\.md\)/',
            function ($matches) {
                return '[' . $matches[1] . '](#doc-' . $matches[2] . ')';
            },
            $markdown
        );

        $html = $this->parsedown->text($markdown);

        // Rewrite the anchor links generated by Parsedown
        $html = preg_replace(
            '/href="#doc-([a-z0-9-]+)"/',
            'href="#" data-doc="$1" class="iwp-doc-link"',
            $html
        );

        return wp_kses_post($html);
    }

    /**
     * AJAX handler for loading docs
     */
    public static function ajax_load_doc() {
        check_ajax_referer('iwp_admin_nonce', 'nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Insufficient permissions');
        }

        $slug = isset($_POST['doc']) ? sanitize_key($_POST['doc']) : 'index';
        $renderer = new self();
        $html = $renderer->get_doc_html($slug);

        wp_send_json_success(array('html' => $html));
    }

    /**
     * Render inline CSS for the docs viewer
     */
    private function render_docs_css() {
        ?>
        <style>
        .iwp-docs-viewer {
            display: flex;
            gap: 0;
            min-height: 500px;
            border: 1px solid #ddd;
            border-radius: 4px;
            background: #fff;
            margin-top: 10px;
        }
        .iwp-docs-sidebar {
            width: 210px;
            min-width: 210px;
            background: #f6f7f7;
            border-right: 1px solid #ddd;
            overflow-y: auto;
        }
        .iwp-docs-sidebar ul {
            margin: 0;
            padding: 0;
            list-style: none;
        }
        .iwp-docs-sidebar li {
            margin: 0;
            border-bottom: 1px solid #e0e0e0;
        }
        .iwp-docs-sidebar li a {
            display: block;
            padding: 10px 15px;
            color: #50575e;
            text-decoration: none;
            font-size: 13px;
            line-height: 1.4;
            transition: background 0.15s, color 0.15s;
        }
        .iwp-docs-sidebar li a:hover {
            background: #e9ecef;
            color: #1d2327;
        }
        .iwp-docs-sidebar li.active a {
            background: #fff;
            color: #2271b1;
            font-weight: 600;
            border-left: 3px solid #2271b1;
            padding-left: 12px;
        }
        .iwp-docs-content {
            flex: 1;
            padding: 25px 30px;
            overflow-y: auto;
            max-height: 700px;
            line-height: 1.7;
        }
        .iwp-docs-content h1 {
            font-size: 22px;
            margin: 0 0 15px 0;
            padding-bottom: 10px;
            border-bottom: 1px solid #eee;
            color: #1d2327;
        }
        .iwp-docs-content h2 {
            font-size: 17px;
            margin: 25px 0 10px 0;
            color: #1d2327;
        }
        .iwp-docs-content h3 {
            font-size: 14px;
            margin: 20px 0 8px 0;
            color: #50575e;
        }
        .iwp-docs-content p {
            margin: 0 0 12px 0;
            color: #3c434a;
        }
        .iwp-docs-content ul,
        .iwp-docs-content ol {
            margin: 0 0 15px 20px;
            color: #3c434a;
        }
        .iwp-docs-content li {
            margin-bottom: 5px;
        }
        .iwp-docs-content code {
            background: #f0f0f1;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 12px;
            color: #1d2327;
        }
        .iwp-docs-content pre {
            background: #f6f7f7;
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 12px 15px;
            overflow-x: auto;
            margin: 0 0 15px 0;
        }
        .iwp-docs-content pre code {
            background: none;
            padding: 0;
            font-size: 12px;
        }
        .iwp-docs-content table {
            border-collapse: collapse;
            width: 100%;
            margin: 0 0 15px 0;
        }
        .iwp-docs-content th,
        .iwp-docs-content td {
            border: 1px solid #ddd;
            padding: 8px 12px;
            text-align: left;
            font-size: 13px;
        }
        .iwp-docs-content th {
            background: #f6f7f7;
            font-weight: 600;
        }
        .iwp-docs-content a[data-doc] {
            color: #2271b1;
            text-decoration: none;
            border-bottom: 1px dotted #2271b1;
        }
        .iwp-docs-content a[data-doc]:hover {
            color: #135e96;
            border-bottom-style: solid;
        }
        .iwp-docs-content blockquote {
            border-left: 3px solid #2271b1;
            margin: 0 0 15px 0;
            padding: 8px 15px;
            background: #f0f6fc;
            color: #3c434a;
        }
        .iwp-docs-content hr {
            border: none;
            border-top: 1px solid #eee;
            margin: 25px 0;
        }
        @media (max-width: 768px) {
            .iwp-docs-viewer {
                flex-direction: column;
            }
            .iwp-docs-sidebar {
                width: 100%;
                min-width: auto;
                border-right: none;
                border-bottom: 1px solid #ddd;
                max-height: 200px;
            }
            .iwp-docs-content {
                max-height: none;
                padding: 15px;
            }
        }
        </style>
        <?php
    }

    /**
     * Render inline JS for sidebar navigation and AJAX doc loading
     */
    private function render_docs_script() {
        ?>
        <script>
        jQuery(document).ready(function($) {
            var $sidebar = $('.iwp-docs-sidebar');
            var $content = $('#iwp-docs-content');

            function loadDoc(slug, pushState) {
                $sidebar.find('li').removeClass('active');
                $sidebar.find('a[data-doc="' + slug + '"]').closest('li').addClass('active');

                $content.css('opacity', '0.5');

                $.post(ajaxurl, {
                    action: 'iwp_load_doc',
                    doc: slug,
                    nonce: '<?php echo esc_js(wp_create_nonce('iwp_admin_nonce')); ?>'
                }, function(response) {
                    if (response.success) {
                        $content.html(response.data.html);
                        $content.scrollTop(0);
                        // Rebind internal links
                        bindDocLinks();
                    }
                }).always(function() {
                    $content.css('opacity', '1');
                });
            }

            function bindDocLinks() {
                $content.find('a[data-doc]').off('click').on('click', function(e) {
                    e.preventDefault();
                    loadDoc($(this).data('doc'), true);
                });
            }

            // Sidebar navigation
            $sidebar.on('click', 'a[data-doc]', function(e) {
                e.preventDefault();
                loadDoc($(this).data('doc'), true);
            });

            // Bind initial content links
            bindDocLinks();
        });
        </script>
        <?php
    }
}
